services:
  - type: web
    name: music-control-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn telegram_bot:app --worker-class sync --timeout 90"
    autoDeploy: true